services:
  - type: web
    name: cv
    env: java
    plan: free
    buildCommand: "./mvnw clean package"
    startCommand: "java -jar target/cv-0.0.1-SNAPSHOT.jar"
    envVars:
      - key: SPRING_MAIL_USERNAME
        value: ngvietanh.it@gmail.com
      - key: SPRING_MAIL_PASSWORD
        value: gjfx daws kxnf ieym
      - key: SERVER_PORT
        value: 10000
